### ISSUE TITLE
As a user, I want to see to which of my contacts do I owe money.

### ISSUE THREAD

**Issue by chenchongsong** [CS2103JAN2018-T11-B4/main#15]

**Comment by Articho28** [comment]
@software-1234  same as before, let me know if I can help you out. Userguide should be ok (double check for me), just handle developer guide please.

**Comment by Articho28** [comment]
@software-1234 Hey Eric, how's this coming along? Can we close this issue by tonight?

**Comment by software-1234** [comment]
yes
