### ISSUE TITLE
Max Feature and Biggest Debtor both in the code and documentation - Remove Duplicate

### ISSUE THREAD

**Issue by Articho28** [CS2103JAN2018-T11-B4/main#48]
Hey @pkuhanan , I noticed that both biggest debtor and max are present while they execute the same tasks. Can you clean that up? 

Thanks!

**Comment by pkuhanan** [comment]
Yup, done here:
https://github.com/CS2103JAN2018-T11-B4/main/pull/50

**Comment by Articho28** [comment]
Sweet, can I close this issue then? Double-checking.
